name: alexfrees
favicon: null
layout_spectrum: 0.15224190382286906
typography_spectrum: 0.09676079987548292
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.06450314377434552
  lightness: 0.6154126559849828
  saturation: 0.2627776444423944
  rhythmicContrast: 0.7971534330863506
purpose: []
